### ISSUE TITLE
Load Projects not displaying

### ISSUE THREAD

**Issue by ericascripted** [popcodeorg/popcode#1004]
![screen shot 2017-08-23 at 1 56 48 pm](https://user-images.githubusercontent.com/13630252/29630761-4207cbaa-880b-11e7-8742-8e205e020333.png)

Can't find my old projects!

**Comment by outoftime** [comment]
N.B. we tracked this down to an issue with Erica’s office WiFi which was causing Firebase requests to fail, but we should show some kind of error message if we can’t fully load projects

**Comment by outoftime** [comment]
Closing in favor of consolidated issue #1009
