### ISSUE TITLE
Can't open snapshot links

### ISSUE THREAD

**Issue by ericascripted** [popcodeorg/popcode#1005]
https://popcode.org/?snapshot=54c4cd46-1488-47d0-bbe6-80c11844f8a6

https://popcode.org/?snapshot=5ec514fe-f8fc-49d0-ab85-e40c810d54ff

**Comment by outoftime** [comment]
N.B. we tracked this down to a partial WiFi outage causing requests to Firebase to fail, but we should certainly show an error message in that case

**Comment by outoftime** [comment]
Closing in favor of consolidated issue #1009
