### ISSUE TITLE
HTML, CSS and JS Tabs obscure first two lines

### ISSUE THREAD

**Issue by jwang1919** [popcodeorg/popcode#1018]
Found an edge case scenario that when a user types something so long that it stretches across the editor, the editor tabs obscure the view.

IE:
![popcode-bug](https://user-images.githubusercontent.com/8751146/30041470-67ce3d4a-91b8-11e7-8244-178d39c6ee4f.png)

**Comment by outoftime** [comment]
Yep, we’ve got it! https://github.com/popcodeorg/popcode/issues/1002

**Comment by jwang1919** [comment]
Cool
