### ISSUE TITLE
Inline code fragments in instructions panel have excessive line height and padding

### ISSUE THREAD

**Issue by jwang1919** [popcodeorg/popcode#1032]
Code in the instructions panel have height that is greater than the standard text leading to very unpleasant looking sentences, especially if they are wrapped between normal text.

See: https://popcode.org/?gist=ca79bdb9b543ae6e6bac57d28e14c1cf
Raw gist link: https://gist.github.com/jwang1919/ca79bdb9b543ae6e6bac57d28e14c1cf

@inlinestyle: @outoftime suggested you look into this.

**Comment by outoftime** [comment]
To clarify we’re talking about inline `<code>` fragments rather than code blocks.

**Comment by outoftime** [comment]
Closed by #1033
