### ISSUE TITLE
Snapshot notification should disappear when project changes

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1048]
Right now, if you:

* Do some stuff
* Create a snapshot
* Leave the snapshot copy prompt open
* Make more modifications to the project

You might be tempted to think that clicking the copy button in the snapshot notification would give you a snapshot of the latest state of your project. But in fact, you’ll still get a link to a snapshot of the state of the project when you clicked **Snapshot**.

Simple fix, I think, is to just make the snapshot notification disappear as soon as the project is changed in some way.

**Comment by iamnickvolpe** [comment]
Do you think this could be solved with my suggestion to simplify this interaction into a single click? In this flow, the snapshot would be created and copied as soon as the "Create Snapshot" button is clicked. And the blue bar is simply an ephemeral notification that let's the user know it's ready to share.

<img width="957" alt="screenshot 2017-11-19 15 36 50" src="https://user-images.githubusercontent.com/3432105/32995230-81050b6e-cd3f-11e7-9582-7894a566b04a.png">

**Comment by outoftime** [comment]
@iamnickvolpe yeah, I do—is there an issue written up with that proposal?
