### ISSUE TITLE
CSS error should include the symbol for semicolon ;

### ISSUE THREAD

**Issue by ericascripted** [popcodeorg/popcode#1101]
Change:

> Looks like you’re missing a semicolon at the end of this line.

To:

> Looks like you’re missing a semicolon (;) at the end of this line.

**Comment by outoftime** [comment]
@ericascripted are you sure we want the “Try” bit? I worry that a lot of students would literally think they should have `color: red` somewhere…

**Comment by ericascripted** [comment]
I copied that from the error that appears when you are missing a colon.

**Comment by outoftime** [comment]
@ericascripted fair enough—do you think it’s a good idea to have it in either message?

**Comment by ericascripted** [comment]
Maybe the wording is, "for example, color:red; "

Erica Wong | Program Manager
*ScriptEd, Inc.*
917-946-4881 <(917)%20946-4881>
85 Broad Street, New York, NY 10004
erica@scripted.org | scripted.org
Follow ScriptEd on Twitter @scriptedorg <http://twitter.com/scriptedorg>

Teach a ScriptEd class <http://scripted.org/volunteer> next school year!

**Comment by outoftime** [comment]
@ericascripted I agree that’s clearer wording, but I still worry about an issue I see in a lot of contexts, namely students seeing example code and copying it verbatim without thinking about which parts apply to their current situation. Maybe better to just leave out the example altogether unless we can use their existing code as a template for it?

**Comment by ericascripted** [comment]
Yep that's definitely something that happens. I don't really feel strongly
about it either way.

Erica Wong | Program Manager
*ScriptEd, Inc.*
917-946-4881 <(917)%20946-4881>
85 Broad Street, New York, NY 10004
erica@scripted.org | scripted.org
Follow ScriptEd on Twitter @scriptedorg <http://twitter.com/scriptedorg>

Teach a ScriptEd class <http://scripted.org/volunteer> next school year!

**Comment by outoftime** [comment]
@ericascripted cool, I’ve updated the PR description accordingly!

**Comment by outoftime** [comment]
Resolved by #1180
