### ISSUE TITLE
Remove placeholder example from missing img src error message

### ISSUE THREAD

**Issue by andymartin-sch** [popcodeorg/popcode#1134]
The error message displayed when an `<img>` tag is missing a `src` attribute gives an example, with a placeholder URL that does not point to an actual image. Experience has indicated that students are apt to copy any example code given verbatim, so in general we’d like to move away from giving examples where part of the example is a placeholder. Given that we cannot anticipate what URL the student might want to use, we should just remove the example from this message altogether.

---

#### Original description:

The error message displayed when you add ```<img src="">``` to a popcode page is:

> ```<img>``` tags need a ```src``` attribute, with the URL of the image you want to display.
Try: ```<img src="http://coolimages.com/image.jpg">```

But loading the image that's linked to (http://coolimages.com/image.jpg) doesn't work, as it's currently returning a 404 error message.

Can this example URL be updated to minimize confusion?

**Comment by outoftime** [comment]
@andymartin-sch interesting—the example there isn’t meant to work, but rather just to show the use of a `src` attribute with a placeholder image. That said, if the message is causing students to type the literal image URL given (which is easy to imagine), I don’t think a working image URL is much better than a non-working one (either way they probably have an image in mind already and we shouldn’t be leading them astray). Perhaps it’s better to just remove the “Try” bit altogether?

**Comment by andymartin-sch** [comment]
Oh interesting, I had always assumed it was a link to a real example image and filed this after a student tried to use the example URL as a sanity check and it didn't work. We then had to go through how to debug the lack of an image appearing by navigating to the image URL directly, etc...

Personally, I don't think it's too misleading to link to an image that does work if/when it's used directly, but I can definitely see it both ways.

**Comment by outoftime** [comment]
@andymartin-sch cool—I think the overall trend is to move away from providing examples like this, since students do often copy them verbatim when they should be thinking through what they are trying to do. More recent discussion of that [in this thread](https://github.com/popcodeorg/popcode/issues/1101#issuecomment-336967029). So my inclination is to fully remove the example here too. I’m going to update the title/description accordingly—thanks!
