### ISSUE TITLE
Archive projects

### ISSUE THREAD

**Issue by connor11528** [popcodeorg/popcode#1136]
Add the ability to archive projects, which hides them from the **My Projects** list but does not actually delete them. Gives coders the ability to keep the projects list organized as they see fit.

Specifications:

* Next to each project title, add an archive icon.
* Clicking the archive icon archives the project. Archived projects are not visible in the **My Projects** list by default.
* However, the **My Projects** interface does expose a “View Archived Projects” button if there are any archived projects. If this button is clicked, archived projects become visible in the list.
* When archived projects are visible, they have an un-archive icon in place of the archive icon. Clicking this restores them to default visibility.

---

#### Original description:

Is it possible to remove projects after they are created?

Perhaps we can have a little x to the right of the project that will ask are they sure they want to delete and then removes the project

![screen shot 2017-10-16 at 6 05 16 pm](https://user-images.githubusercontent.com/3578908/31641897-a9955ca4-b29c-11e7-9bc2-8aef213d1673.png)

**Comment by outoftime** [comment]
@connor11528 definitely agree there should be a way to hide projects from the list. However I worry that a permanent delete button will be too error-prone, [even with a confirmation prompt](http://alistapart.com/article/neveruseawarning). Better imo to make it an “archive” feature where the project isn’t fully deleted, but rather is just hidden by default from the list; a “View Archive” would allow users to see projects they have archived and present an un-archive button on those projects. WDYT?

**Comment by connor11528** [comment]
For sure archive feature could be good and is a way for students to look back on all of their projects and work. I like the snapshot feature and think it's great that students can have unique links to save their work.

I think it is a bit unclear how creating a snapshot creates a new project but clicking New Project does not add a new project to the Projects list. For example, when we type something and click snapshot the project gets added to the My Projects list. If we click New Project we get a fresh project but no new project in the My Projects list.

Perhaps we can make these more explicit, such as **Save project** instead of snapshot. New Project could say something like clear screen. This relates to #1128 in that if the project is saved we could write **Saved ☑️** based on if the code is saved as a project. If a user has written code but not saved it as a project we could display "not saved" or "save project"

**Comment by outoftime** [comment]
@connor11528 I definitely agree that it’s confusing that freshly-created projects don’t appear in *My Projects*, and we should change that. However Popcode’s behavior with respect to saving your work is a little different from what you describe here:

* When you create a new project, as long as you’re logged in, the project is automatically saved as soon as you make any modification to it, and each subsequent modification is automatically saved
* A new project also appears in the **My Projects** list as soon as the coder makes any modification to it
* The **Snapshot** feature is completely separate—this simply creates a stable link to the current state of the project, and can be used regardless of login state

Anyway, I’ve created a [separate issue](https://github.com/popcodeorg/popcode/issues/1137) to capture the desired behavior of the projects list, and I’m going to update the title/description of this issue to clarify the archiving behavior.

**Comment by connor11528** [comment]
Okay interesting. thank you @outoftime 

looking forward to digging into this more. I'm new to react (mostly use vue) but definitely worth looking at. great project
