### ISSUE TITLE
Security error when executing jQuery handler

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1190]
Submitter: Marcela Pagoada
Email: mpagoada@westinghousehs.org
Please see this snapshot:

https://popcode.org/?snapshot=f8357eeb-ba1c-4eb8-a2f7-2ddd72933ef6

Click on the “yes” button and notice that a security error occurs.

Observed on Chrome 38.0.2125.104

**Comment by catrope** [comment]
This is probably a duplicate of #581 , right?

**Comment by outoftime** [comment]
@catrope yep!
