### ISSUE TITLE
Blank Page Title on Load

### ISSUE THREAD

**Issue by iamnickvolpe** [popcodeorg/popcode#1205]
The page title in the preview pane is empty when the application is first loaded.

### Steps To Reproduce

1. Load the application

<img width="1196" alt="screenshot 2017-11-19 17 15 35" src="https://user-images.githubusercontent.com/3432105/32996179-9b90bff6-cd4d-11e7-8492-ef11405d8f84.png">

**Comment by outoftime** [comment]
Fixed by #1269
