### ISSUE TITLE
justify-content: space-evenly; not recognized

### ISSUE THREAD

**Issue by catrope** [popcodeorg/popcode#1246]
One of the students in our class was looking at [the CSSTricks Flexbox guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and trying out different `justify-content` values, and found that `justify-content: space-evenly;` was [rejected](https://popcode.org/?snapshot=acece799-8503-4c79-90be-24dfc3e65918) by Popcode.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#Browser_compatibility), `space-evenly` is pretty new: it's supported in Chrome 60+ (current version is 63), Firefox 52 (current is 57) and not at all in IE/Edge.

**Comment by outoftime** [comment]
Will probably need to patch PrettyCSS to support this.

**Comment by catrope** [comment]
I did: https://github.com/popcodeorg/PrettyCSS/pull/2 . Not sure why it
wasn't automatically linked here.

**Comment by catrope** [comment]
@outoftime informed me that I needed to submit that pull request upstream instead, so I did: https://github.com/fidian/PrettyCSS/pull/53

**Comment by outoftime** [comment]
@catrope saw that your PrettyCSS PR got merged—want to cut a PR for Popcode that targets the current head on GitHub until the next release?
