### ISSUE TITLE
Capture console.log in JavaScript code and propagate it to the console

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1249]
If the regular JavaScript code contains a call to `console.log`, the message should appear in the Popcode JavaScript console. This means we will need to either replace the `console` object entirely in the preview environment, or overwrite the `log` method. For completeness, we might as well handle `debug`, `info`, `warn`, `error` as well.

We should make sure _not_ to break any other built-in console methods (e.g. `console.time()`).

I think it makes sense for calls to `console.log` and friends to still appear in the browser’s JavaScript console—so when we override the built-in functionality, we should hold references to the original methods and call them as well.

**Comment by alexpelan** [comment]
Looking at this: https://developer.mozilla.org/en-US/docs/Web/API/console#Outputting_text_to_the_console

I think for initial scope, I'm going to ignore both 'Using string substitutions' and 'Styling console output' These will both gracefully degrade in the Popcode console, just displaying literaly `%s` and `%c`

**Comment by outoftime** [comment]
Seems entirely reasonable!
