### ISSUE TITLE
Handle up/down arrows in console

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1258]
Pressing the up/down arrows in console should allow you to cycle through the history of your console entries, just like in most other REPLs.

Maybe we should also consider some sort of visual way of doing this? E.g. maybe a subtle button on the right side of each printed entry in the console that, when clicked, populates the input with a copy of that entry.

**Comment by razzius** [comment]
I'm planning to give this a go at the next Popcode contributor night, Monday July 30th

**Comment by outoftime** [comment]
Closed by #1531
