### ISSUE TITLE
Clear console

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1259]
You should be able to clear the console entries by:

* Clicking a button somewhere (probably in the console label)
* Pressing control-L (this is more of a nice-to-have but probably pretty easy to add)
* Calling `console.clear()`

**Comment by alexpelan** [comment]
Should we also support `console.clear()` here?

**Comment by outoftime** [comment]
@alexpelan sure!

**Comment by outoftime** [comment]
Fixed by #1302
