### ISSUE TITLE
Runtime errors thrown by console statements should be mapped to user-friendly messages

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1260]
Just as we map runtime errors in project code to user-friendly messages, we should also map them when outputting them in the console. We may need to map a few more errors than we have currently, but the one or two that we currently handle would be a good start.

**Comment by omardeleo** [comment]
Hey Mat, I believe I've got a solution here. Interested in hearing your thoughts when you get a chance, thanks!

## Implementation Outline

-   Inside `async _evaluateConsoleExpression(key, expression)` in the `PreviewFrame` component, modify the arrow function passed to the caller's `error` handler.
-   Inside the arrow function, initialize variable `errorMessage`.
- If `(message === 'Loop Broken!')`, set `errorMessage = t('errors.javascriptRuntime.infinite-loop')`.
- If `(name === 'TypeError')`:
  * generate `ErrorConstructor` to construct error;
  * create variable `normalizedError` and assign it the normalized constructed error;
  * assign `errorMessage = normalizedError.message`.
 - Check to see if `errorMessage` has been assigned a value. If not, assign it the original `message` argument that was passed to the arrow function.
 - Pass `errorMessage` as argument to the `message` parameter of `this.props.onConsoleError()`.

**Comment by outoftime** [comment]
Fixed by #1260
