### ISSUE TITLE
Minimize preview button

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1340]
In the summer 2017 redesign, we in haste removed the old minimize button from the layout and did not replace it. I think a down chevron on the right side of the title bar, next to the refresh button, would do just fine. All the actual code to handle showing/hiding the preview is still in place so we should just need a button to actually do it.

**Comment by alexpelan** [comment]
I can do this one

**Comment by outoftime** [comment]
Apparently someone at GitHub forgot a beginning-of-line anchor in their regexp…
