### ISSUE TITLE
can't install on windows

### ISSUE THREAD

**Issue by Rosmeee** [popcodeorg/popcode#1353]
l am trying to run `yarn` on Windows..

Here are the errors:
![image](https://user-images.githubusercontent.com/25814612/36434240-8e7aaca6-1699-11e8-8ae5-0ccb607b28b2.png)

my yarn version is 1.3.2 and l install yarn through `npm install yarn -g`,
l am not familiar with how yarn work, can anyone tell the problem?

**Comment by outoftime** [comment]
@jwang1919 maybe you can help with this?

**Comment by jwang1919** [comment]
Hi @Rosmeee, I strongly recommend against installing yarn this way especially if you are on Windows.

In addition the official site warns you against installing Yarn via npm:

> Note: Installation of Yarn via npm is generally not recommended. When installing Yarn with Node-based package managers, the package is not signed, and the only integrity check performed is a basic SHA1 hash, which is a security risk when installing system-wide apps.

> For these reasons, it is highly recommended that you install Yarn through the installation method best suited to your operating system.

I like installing yarn via Chocolatey instead. There are instructions listed on the [Yarn Official Installation Page for Windows](https://yarnpkg.com/en/docs/install). If you aren't comfortable with that, there is an .msi installer you can download instead.

**Comment by Rosmeee** [comment]
@jwang1919  Thanks for replying! l have removed yarn and install it using .mis installer but still fail. lt seems something wrong with node-pre-gyp? My node version is 8.9.4, is it able to install?

**Comment by jwang1919** [comment]
Great! Maybe what fixed it was a computer restart.

**Comment by jwang1919** [comment]
@outoftime This issue can be closed.

**Comment by outoftime** [comment]
Glad it worked out!
