### ISSUE TITLE
Only allow gist export when logged in with GitHub-linked account

### ISSUE THREAD

**Issue by Krinkle** [popcodeorg/popcode#1363]
Since GitHub is sunsetting anonymous gists, we should only show the Create Gist button if you’re logged in to a GitHub-linked account. We already do this for the repo export button (in experimental mode).

We should also be able to simplify some of the logic in the `github` client since it no longer needs a code path for anonymous export.

Original report below:

---

Hi,

I noticed just now when viewing something on popcode that one can "Export to Gist" even without being logged in. This produces an anonymous Gist and redirects the browser tab to its url.

GitHub announced earlier this year that they'll disable this feature soon (next month).

https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/

**Comment by outoftime** [comment]
Good looking out @krinkle! Gonna update the description to lay out action items.

**Comment by outoftime** [comment]
@Krinkle is this something you’d be interested in putting together a PR for?

**Comment by Krinkle** [comment]
@outoftime Thanks for asking but no, not in this case. Maybe another time :-)
