### ISSUE TITLE
System requires python to be installed

### ISSUE THREAD

**Issue by jwang1919** [popcodeorg/popcode#1449]
Listing this as a bug because python was previously not a requirement to run Popcode.

Error occurs when running `yarn` on a Windows 10 64bit machine.

```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\Projects\ScriptEd\popcode\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\Projects\ScriptEd\popcode\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\Projects\ScriptEd\popcode\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:149:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Projects\\ScriptEd\\popcode\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\ScriptEd\popcode\node_modules\iltorb
```

**Comment by jwang1919** [comment]
Seems like installing Python is not enough, more configurations need to be done for Windows machines for `node-gyp` to work.

**Comment by jwang1919** [comment]
Was able to get it working after following directions listed: https://github.com/nodejs/node-gyp to install `node-gyp`. Another "wrinkle" is I had to run this through Windows Powershell with admin privileges.

@outoftime Can you confirm that `node-gyp` is required to be globally installed to run Popcode now? Or is this some Windows specific error?

**Comment by outoftime** [comment]
@jwang1919 thanks for checking, and sorry for the PITA with `node-gyp`. Pretty sure that package is the cause of 95% of NPM install headaches.

The good news: though I didn’t realize it at the time, it appears that #1456 got rid of `node-gyp` as a (sub-)dependency. So hopefully you should be OK now? Can you confirm and close this issue if so?

**Comment by jwang1919** [comment]
Yep looks good 👍
