### ISSUE TITLE
Confusing behavior when using a variable called "name" in Popcode

### ISSUE THREAD

**Issue by greenberga** [popcodeorg/popcode#1453]
For one of the for-loop/array assignments, one of my students created an array of students and assigned it to a variable called `name`. For some reason, the variable is being coerced to a string (as if all the array elements were joined together with a `,`). Seems like a bug? Confusing behavior, at least.

![weird-coercion](https://user-images.githubusercontent.com/38597857/39733499-f7ac01a6-5240-11e8-935c-cd971b8474db.png)

**Comment by alexpelan** [comment]
This bug rules - I had to see it for myself.

if your JS code is just `console.log(name)` then it logs the name of the preview iframe - so some sort of global pollution of that variable is happening

**Comment by outoftime** [comment]
This is mystifying, but good catch @ajgreenb and good investigation @alexpelan !

**Comment by outoftime** [comment]
Wait! This isn’t a bug! Try it in the browser console : D
