### ISSUE TITLE
Unable to export/update repo when Instructions panel is opened

### ISSUE THREAD

**Issue by jwang1919** [popcodeorg/popcode#1478]
Adding instructions and having the instructions panel open throws a visible "Something went wrong trying to export that repo. Please try again." error.

Interestingly, if the instructions panel is closed, the export/update repo functionality works fine.

Ex: https://popcode.org/?snapshot=79aadac1-2e26-4e1d-8757-0f745fd5ba18

**Comment by alexpelan** [comment]
@jwang1919 can you still reproduce this? I cannot. The issue still persists with the snapshot above, but I changed snapshots to no longer save references to the saved github repos, so I would be interested to see if you could make it happen with a new repo, or whether it was fixed by that change.

**Comment by jwang1919** [comment]
Yep can confirm the bug is fixed now!
