### ISSUE TITLE
Update Firebase Auth and Linking methods

### ISSUE THREAD

**Issue by pwjablonski** [popcodeorg/popcode#1552]
After remaining logged with Google this warning message appears in the console 

```firebase.auth.Auth.prototype.signInWithCredential is deprecated. Please use firebase.auth.Auth.prototype.signInAndRetrieveDataWithCredential instead.```
(edited)

same for this

```firebase.User.prototype.linkWithCredential is deprecated. Please use firebase.User.prototype.linkAndRetrieveDataWithCredential instead.```

Resources
- https://firebase.google.com/docs/auth/web/account-linking
- https://firebase.google.com/docs/reference/unity/class/firebase/auth/firebase-auth

**Comment by omardeleo** [comment]
Hi @pwjablonski, did you see those console messages in development, or in production? I've logged into both with Google and haven't seen them. I can, of course, update these methods anyway, but am curious to see if I can replicate the warning.

**Comment by outoftime** [comment]
Closed by #1600
