### ISSUE TITLE
Zoom enlarged by default

### ISSUE THREAD

**Issue by connor11528** [popcodeorg/popcode#1554]
We've had some issues at our school in Oakland with students not being able to read the text or distinguish between l's and 1's. After zooming in to make the text larger it was much easier for them to read.

Could we have the default view for popcode to be large and make it a button to decrease size, rather than the other way around?

Thank you!

**Comment by outoftime** [comment]
@connor11528 Thanks for flagging this! I’d be hesitant to default to the larger zoom level—it’s intended for situations where we need unusually large text, like a projector. But i’m definitely open to the idea that the current default font size in the editor is too small. A couple of questions:

* What screen resolution is being used by the students in your class? http://whatismyscreenresolution.net/ is an easy way to grab this info
* Using the browser’s zoom functionality, (command-`+` / command-`-`), what is the minimum zoom that your students find easy to read?

Thanks!

**Comment by connor11528** [comment]
I think they have Acer chromebook 14 so 1,366x768

Not sure about the minimum but some larger font would be helpful
