### ISSUE TITLE
Images in instructions should be scaled to fit width of instructions pane

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1573]
Right now an image that’s wider than the instructions pane will bleed off the edge. We should set a max width of 100% of the instructions pane or something equivalent.

Might as well set a sensible max height (maybe 50vh or something) while we’re at it.

Example of bad current behavior:

https://popcode.org/?snapshot=869ce967-a7c7-4907-92e9-0924203f3d0c

**Comment by EricSnell** [comment]
Happy to take this on! 👍

**Comment by igrib** [comment]
Sure. I'll take a look at another issue.

**Comment by igrib** [comment]
I didn't start on it yet. So Eric can take it.

**Comment by EricSnell** [comment]
Sorry about that igrib! I"m happy to look into another issue if you'd still like to dive into this one 👍

**Comment by igrib** [comment]
Go for it. I won't get to an issue until later.
