### ISSUE TITLE
No error for text/tags outside the body

### ISSUE THREAD

**Issue by mallorybulkley** [popcodeorg/popcode#1581]
No error for putting plain text outside of the body, as well as plain text or other tags outside of the html tags.
Would also be great if we could detect plain text (not in an enclosing tag) _inside_ the body, tho that seems more difficult. A lot of students struggle with this, since their text does show up on the page, they don't see a problem.

See: https://popcode.org/?snapshot=0a260e86-b67b-4dc4-b2d1-d3d5e145db98

**Comment by outoftime** [comment]
@mallorybulkley agree about the stuff outside the body—longstanding blind spot in Popcode’s HTML validation—but I think it’s perfectly fine to put text directly _inside_ the `<body>` tag?

**Comment by mallorybulkley** [comment]
@outoftime yeah, technically fine but in the curriculum we've been instructing them to put everything inside of a tag. Mainly an issue when trying to teach them <p> tags for the first time. If popcode had a linter/warning option instead of just full error that would probably make more sense. But probably not worth adding that functionality
