### ISSUE TITLE
Validation error when the href in <a> tags is (probably) missing a scheme

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1588]
If a student creates an a tag along the lines of `<a href="scripted.org">`, this will lead to `https://popcode.org/scripted.org`, because that’s just how links work. However given that this is a common mistake, especially among beginners, we should detect this situation and display a validation error. We will need to detect it heuristically, but I think “relative path whose first segment contains a `.`” is probably sufficient.

Original report below.

---

Submitter: Ilya Gribov
Email: gribov@gmail.com
If you do not include http:// or https:// with anchor tags, clicking the link takes you to a popcode.org sub directory. Either we need to force students to include http/https through an error message or allow it to work properly without it. Forcing them to add http or https opens up a can of works regarding SSL/TLS.
Example: https://popcode.org/?snapshot=9daa27b6-4021-4c74-865e-a6b6f347d411

**Comment by outoftime** [comment]
@igrib this isn’t a Popcode thing—that’s just the behavior of links that don’t have a protocol in the URL. The browser treats them as relative links. I definitely think there’s an argument for adding a validation to heuristically detect this mistake (basically relative links where the first “path element” has a period in it) and expose a validation error, what do you think?

**Comment by igrib** [comment]
Hi Mat,

I never thought about it; it makes sense. I just saw a lot of confusion
with students and was hoping to clear it up with an error message.

**Comment by outoftime** [comment]
Closed by #1602
