### ISSUE TITLE
Extra pristine project appears after logging in

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1589]
This is a preexisting bug made visible by #1137. To reproduce:

* Open Popcode
* Log in
* Open the **Your Projects** list
* Expect a single pristine (no timestamp) project to be in at the top of the list, highlighted
* Observe that two pristine projects are at the top of the list, with the second one highlighted:

  ![image](https://user-images.githubusercontent.com/14214/46905665-ff7b9080-cec4-11e8-9f2a-1d6491da6eb3.png)

This can also be reproduced by opening Popcode directly while already logged in.

I’m guessing we are creating an extra pristine project at some point in the process of logging you in, which was never noticeable before.

Clicking the **New Project** button, or switching projects, fixes the problem for the duration of the session.

**Comment by outoftime** [comment]
@jwang1919 maybe relevant to your interests if you’ve got the energy to tackle another one!!

**Comment by jwang1919** [comment]
Hmm.. interesting, I guess this bug was never visible before. Yeah I can take a look into this.

**Comment by jessewang-arvatosystems** [comment]
bump

**Comment by outoftime** [comment]
Hmm! Yep, I can’t reproduce it either now @jwang1919
