### ISSUE TITLE
Update image on README.md

### ISSUE THREAD

**Issue by jwang1919** [popcodeorg/popcode#1590]
The Popcode demo image on README.md is the OG Popcode.
While it's nice to look at from a historical perspective, I think it can use an update.

Maybe someone with photoshop skills can whip up the nice image for the current Popcode build.

**Comment by outoftime** [comment]
@jwang1919 haha, anybody with basic screengrab skills should be able to handle it : )

**Comment by igrib** [comment]
@outoftime I'll give it it a short just to get the workflow figured out.

**Comment by outoftime** [comment]
Closed by #1592
