### ISSUE TITLE
Fragment-only URLs should be allowed in <a> tags

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1608]
We recently rolled out [a check for unintended relative links in `<a>` tags](https://github.com/popcodeorg/popcode/pull/1602), e.g. `<a href="codenation.org">`. However, the way the rule is constructed also catches fragment-only tags, e.g. `<a href="#interests">`; these links will work fine in Popcode and should not be considered an error.

[This snapshot](https://popcode.org/?snapshot=cf96061d-0b05-400a-a80e-df97d477b5f0) demonstrates the bug.

**Comment by outoftime** [comment]
@alecmerdler are you able to pick this up as a followup to #1602 ?

**Comment by alecmerdler** [comment]
I've made a PR upstream to `htmllint`, I think that's the best solution.

**Comment by outoftime** [comment]
@alecmerdler great! generally my approach is, unless they’re really quick responding to the PR, to just temporarily target our fixed branch directly on GitHub until it’s merged and released upstream. Would that work in this case?

**Comment by alecmerdler** [comment]
That seems fine, I don't think I've ever added a branch of a forked repo as a dependency before. Hopefully it will get merged soon, though.
