### ISSUE TITLE
Compile modern JavaScript for compatibility with older browsers

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1620]
Currently, Popcode doesn’t prevent the use of modern JavaScript (ES6+) syntax and features—[this snapshot](https://popcode.org/?snapshot=a04ed3c3-c4ad-40d8-adda-83831b669602) works just fine on modern Chrome, for instance—but it doesn’t do anything to make newer JavaScript work on older browsers. Since many of our students are stuck on old browser versions, this creates an inconsistency in what kind of code they can actually write, and presents an obstacle to teaching modern JavaScript.

So, let’s pull Babel into the application and compile the students’ JavaScript down to a spec that the current browser can handle. A few thoughts/challenges:

* Ideally, we’d only do as much compilation as the current browser requires. In theory this should be entirely possible with `babel-preset-env`, though we will need to be careful about not making the bundle enormous with a big browser compatibility data file. If that’s unavoidable with `preset-env`, we can just compile everything down to a version that works on all browsers that Popcode supports (which is of course what Popcode’s own application runtime does)
* We should make sure to include the runtime polyfills as well as compiling the code, although I think that’s already baked in to support the `previewSupport` runtime.
* This may be as good a time as any to introduce web workers to the Popcode universe—I suspect the compilation step could have substantial performance implications if run synchronously in the document’s execution context. I’ve been wanting to move things like validations to web workers for a while anyway.
* One thing to look out for is making sure we are still reporting the correct line number in the student’s JS source for runtime errors. This will probably require generating inline source maps. If this is at all complicated, we can punt it to a followup (but should probably do the initial release in experimental mode)
* Once we have the general framework in place, also as a followup, we should do the same thing for CSS, adding automatic browser prefixing and support for compiling newer CSS features for older-browser support where possible

**Comment by wylieconlon** [comment]
I'm going to begin this
