### ISSUE TITLE
Unable to retrieve location via Geolocation API on Popcode.

### ISSUE THREAD

**Issue by srish** [popcodeorg/popcode#1625]
I want to geo search for wiki pages near me using [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) + Wikipedia [Geosearch API](https://www.mediawiki.org/wiki/API:Geosearch). It is a demo for a workshop planned with high school students around Wikipedia APIs.

Here is a link to the Snapshot in Popcode> https://popcode.org/?snapshot=27e76c6e-ae6a-4314-903d-da8f6048ae26. The code works locally and on Codepen as well. But, the first part of the demo which is to retrieve location via Geolocation is not working on Popcode.

I'm guessing due to privacy concerns Popcode might be blocking access to such APIs but don't have much clue. Could one of the maintainers share what might be the issue and what could be the workarounds if any?

**Comment by wylieconlon** [comment]
@srish When I try your code in Chrome, I get an error message that links me to this page explaining the error: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

Based on the error message, the core issue is that Popcode renders its preview using an iframe without the code being hosted on the same domain, which Chrome restricts the permissions of by default. I looked at codepen, and they appear to serve their previews from a subdomain, which Chrome treats differently.

This looks like it's related to #1473, in that the solution to both is similar.

**Comment by outoftime** [comment]
Heyo! This is a specific case of the general class of bugs that would be fixed by https://github.com/popcodeorg/popcode/issues/804 . Closing this issue but will retain a reference to it in the main one. Thanks!
