### ISSUE TITLE
Divider missing when html collapsed

### ISSUE THREAD

**Issue by pwjablonski** [popcodeorg/popcode#1676]
The draggable divider disappears when the both the CSS and JS editors are open and the HTML editor is collapsed.

![Screen Shot 2019-04-04 at 1 09 46 PM](https://user-images.githubusercontent.com/9774128/55574726-144e1980-56db-11e9-817a-91ce8bb37884.png)

**Comment by ianplunkett** [comment]
@pwjablonski I'd be interested to take this on if it's available.

**Comment by pwjablonski** [comment]
Hey @ianplunkett that sounds good to me! @outoftime okay if I assign Ian and move it over into the contributor night project board?
