### ISSUE TITLE
Cannot read property 'split' of null

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1720]
## Error in Popcode

**TypeError** in **/**
Cannot read property 'split' of null

[View on Bugsnag](https://app.bugsnag.com/popcode/popcode/errors/5d2cae7e0094900018ec7820?event_id=5d2caea4004a96fbb2a80000&i=gh&m=ci)

## Stacktrace

    src/components/TopBar/CurrentUserMenu.jsx:48 - renderItems
    src/components/TopBar/createMenu.jsx:81 - Menu

[View full stacktrace](https://app.bugsnag.com/popcode/popcode/errors/5d2cae7e0094900018ec7820?event_id=5d2caea4004a96fbb2a80000&i=gh&m=ci)

*Created by Matthew Brown via Bugsnag*

**Comment by outoftime** [comment]
@MaggieWalker looks like this is happening when `displayName` is null—are you down to add a check for that?

**Comment by MaggieWalker** [comment]
@outoftime 

Yep, can do!

**Comment by outoftime** [comment]
Great, thanks @MaggieWalker—I have [reverted your original PR](https://github.com/popcodeorg/popcode/pull/1721) as the error is causing user-facing crashes; your best bet is to just start with a revert of the revert, and then add in a fix for the null `split` error. Feel free to ping me on Slack if you run into any trouble!

**Comment by MaggieWalker** [comment]
Got it, @outoftime . Will ping you if needed!

**Comment by outoftime** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **/**](https://app.bugsnag.com/popcode/popcode/errors/5d2cae7e0094900018ec7820?event_id=5d2cdb9f004aa41b49f60000&i=gh&m=fx)
