### ISSUE TITLE
Experiment with switch from Webpack to Rollup

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#1888]
Rollup apparently has much lower per-module overhead and better tree shaking, so quite possibly could substantially reduce load and parse time over Webpack. However we do rely heavily on various affordances available in Webpack and its ecosystem, so not clear whether a migration would be possible without a ton of work. Goal here is just to establish whether there are any huge hurdles to using Rollup, and if not, whether a quick-and-dirty Rollup build would give us substantial performance improvements.

**Comment by outoftime** [comment]
Environment variables: https://www.npmjs.com/package/rollup-plugin-env

**Comment by wilsonj806** [comment]
I can check this out! Is there any other objectives asides from meeting the above objectives and how do you want the results reported?

**Comment by outoftime** [comment]
Nice @wilsonj806 ! I started a spike on this a while ago, just rebased the branch and pushed it [here](https://github.com/popcodeorg/popcode/compare/master...outoftime:rollup), so that might be useful. Where I left it was an issue where certain UMD modules, after being processed by babel, weren’t recognized by the `commonjs` plugin; but if I put the `commonjs` plugin first, it barfed on JSX files because it only parses standard JS. I _think_ the move is probably just to build two Babel passes into the plugin chain—one that _only_ compiles JSX to regular JS, done before `commonjs`; and one that applies the rest of the transforms after `commonjs`. But I’m open to other approaches if you think there’s a better one!

In terms of objectives, basically I just want to establish whether a working and functionally equivalent Rollup bundle is meaningfully smaller than what Webpack produces now. So in terms of results reported, basically:

* A branch that I can check out and see that the app works
* Comparison of combined bundle sizes when compiled in production mode

That all make senser?

**Comment by wilsonj806** [comment]
Yep makes sense!

**Comment by wilsonj806** [comment]
Quick update but I've got it up and running locally and have messed with it a bit. Ran into the below issues, but not sure if it's the same stuff you ran into:
- Weird transpilation error/ issue where importing default exports like: `import LRU from 'my-module` didn't work
  - sort of hacked the solution to get past it
- Error: UMD and IIFE output formats are not supported for code-splitting builds
  - this seems like a general issue with Rollup

Will need to play with Rollup some more to see.

**Comment by outoftime** [comment]
Thanks for the update @wilsonj806! Feel free to open a draft PR with your progress so far, Iʼd love to check it out.

> Weird transpilation error/ issue where importing default exports like: import LRU from 'my-module didn't work

Is this a general issue or just when importing from that one package?

> UMD and IIFE output formats are not supported for code-splitting builds

Could this have to do with the JSX compilation thing I mentioned before? Running CommonJS modules through Babel seems to interfere with the Rollup CommonJS pluginʼs ability to properly transform UMD. But I did not notice any connection between that phenomenon and code splitting so maybe two separate issues.

> Some part of the Rollup plugins seems to have issues figuring out require() syntax and import syntax

Same question about plugin order here

**Comment by outoftime** [comment]
Per #2289, it does not appear that a switch to Rollup nets us any particular improvements in bundle size. Asked and answered!
