### ISSUE TITLE
CSS editor does not support webkit filter/filter

### ISSUE THREAD

**Issue by jwang1919** [popcodeorg/popcode#190]
Popcode reads -webkit-filter and filter as invalid properties.

**Comment by outoftime** [comment]
@jwang1919 so, I have learned some things:

* `filter` is not part of a stable CSS spec. It’s a [W3C working draft](https://drafts.fxtf.org/filters/#FilterProperty)
* It’s [not supported whatsoever by IE](http://caniuse.com/#feat=css-filters)
* Only the [most recent release of Chrome (end of August) started supporting it unprefixed](http://caniuse.com/#feat=css-filters)

With that in mind, do you think Popcode should support it?

**Comment by jwang1919** [comment]
Yes because Cloud9 supports use of the `filter` property.
EX: https://raw.githubusercontent.com/jwang1919/ScriptEdBasketball/master/screenshot.png

Ultimately if we're going to transition students from Popcode to Cloud9, any CSS valid in Cloud9 should be valid in Popcode. My thought is that (in our past experiences) some students like to prototype their code in JSBin before deploying to Cloud9. If we invalidate the `filter` property in Popcode, students might assume it won't work in Cloud9.

**Comment by outoftime** [comment]
@jwang1919 But Cloud9 isn’t a learning tool—it’s just a coding environment. it also “supports” CSS properties like `silliness` and `marshmallows`, in the sense that it doesn’t complain if you use them, right? Ultimately students can use non-standard properties in Cloud9 as long as the browser they’re using supports them, but I think we need to figure out independently where Popcode should draw the line (for instance, I can guarantee lots of students at GWHS are using a version of Chrome that doesn’t support `filter`).

**Comment by outoftime** [comment]
Actually, I stand corrected that Cloud9 treats `filter` and `marshmallows` the same—it does pop up an “invalid property” warning for the latter.

My point remains, though, that depending on what laptop they use that day, students may still find that `filter` does not work for them…

**Comment by outoftime** [comment]
OK, giving it some more thought—the point of Popcode is to notify students of *mistakes* in their code. Using `filter` isn’t a mistake—it might not work in some browsers, but it’s not a mistake. So, Popcode should support it.

**Comment by jwang1919** [comment]
@outoftime The point about the outdated Chrome versions does make sense. I would still argue in favor of `filter` because it's more of a school IT issue than a Popcode issue. Also older versions of Chrome do support the `-webkit-filter` property,

Maybe we can reach a middle ground and add a warning saying something like "The CSS property 'filter' is an experimental property that might not work in some browsers".

**Comment by jwang1919** [comment]
Or we can figure this out democratically with a vote among contributors as well as from ScriptEd volunteers.

**Comment by outoftime** [comment]
Just to update since we moved back from Trello—the issue is band-aided, but ultimately we need to fix `PrettyCSS` upstream to get real validations.

**Comment by jwang1919** [comment]
Sounds fun. What about the alternative of using another CSS linter?

**Comment by outoftime** [comment]
@jwang1919 we would need to get rid of PrettyCSS entirely, and at this point I don’t know of another CSS linter that validates not just properties but values with respect to properties (e.g. it will tell you that `color: 50%` is not valid even though `width: 50%` is). I think for that reason it’s worth keeping around and worth contributing upstream (I already added Flexbox support, and it wasn’t too bad)

**Comment by jwang1919** [comment]
Already resolved this ticket! See PR #215
