### ISSUE TITLE
No error prompt on closing curly brace in CSS section

### ISSUE THREAD

**Issue by jwang1919** [popcodeorg/popcode#191]
Popcode will read the following CSS as valid with no error prompt.
`p {
    color: black;
`

**Comment by outoftime** [comment]
I think the fix for this is to incorporate [`stylelint`](https://github.com/stylelint/stylelint), which does report this as an error.

**Comment by outoftime** [comment]
@jwang1919 this would be useful and possibly juicy and fun if you are looking for a meaty contribution!

**Comment by jwang1919** [comment]
I'll work on it the week after. I got other commitments this weekend 😄 .

**Comment by jwang1919** [comment]
@outoftime please assign this to me. I can't find any option to do so myself. I'll start doing some basic digging into this issue.

**Comment by outoftime** [comment]
@jwang1919 all yours!!

**Comment by outoftime** [comment]
Fixed by #556
