### ISSUE TITLE
HTML editor doesn't error when there is HTML outside of the body and head tag

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#202]
Submitter: jane
Email: jane@janekim.me
HTML editor doesn't error when there is HTML outside of the body and head tag

e.g.
<head></head>fjewiofjioew<body></body> doesn't error

**Comment by outoftime** [comment]
Absolutely, this is a problem. Unfortunately neither `htmllint` nor `slowparse` complains about this—I do want to explore whether it would be possible to get them to do it, either by patching them in the runtime or forking them and adding checks for this.

**Comment by jwang1919** [comment]
Similar issue regarding text in the `head` tag, if text is placed after the `<title>`.
The following will be valid in Popcode:
```
<head>
        <title>Page Title</title>
        asdf
</head>
```

**Comment by outoftime** [comment]
Merged into https://github.com/popcodeorg/popcode/issues/378, which catalogs a bunch of similar issues with enforcement of high-level document structure.
