### ISSUE TITLE
Holding down 'd' or 'f' in CSS section will freeze the site (or having more than 23 of these characters)

### ISSUE THREAD

**Issue by jwang1919** [popcodeorg/popcode#210]
Not sure why this bug is happening, but found this by randomly holding keys down in the CSS panel.

If you hold the `d` or `f` key (and their uppercase equivalents) in the CSS panel, the first 23 keys are entered, then the site freezes. Strangely enough holding down other keys will not freeze the site.

**Comment by outoftime** [comment]
@jwang1919 odd one! probably not the top-priority bug but I’m definitely curious as to why those two keys in particular do it…

**Comment by jwang1919** [comment]
Yeah it's very strange. It has nothing to do with holding down the key though but instead with having more than 23 of either character with freeze the site.

**Comment by jwang1919** [comment]
Can't reproduce this bug anymore. Maybe the stylelint library fixed it?

**Comment by outoftime** [comment]
!
