### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#2121]
## Error in Popcode

**TypeError** in **/**
Cannot read property 'toString' of undefined

[View on Bugsnag](https://app.bugsnag.com/popcode/popcode/errors/5e3425f52cddbb001afdcfd8?event_id=5e3432a80055e473fa0f0000&i=gh&m=ci)

## Stacktrace

    validations/Validator.js:26 - t.value
    validations/javascript/esprima.js:102 - t.value
    validations/Validator.js:33 - t.value
    validations/Validator.js:21 - t.<anonymous>

[View full stacktrace](https://app.bugsnag.com/popcode/popcode/errors/5e3425f52cddbb001afdcfd8?event_id=5e3432a80055e473fa0f0000&i=gh&m=ci)

*Created by Matthew Brown via Bugsnag*

**Comment by outoftime** [comment]
This issue has been linked to an error in Bugsnag
[**TypeError** in **/**](https://app.bugsnag.com/popcode/popcode/errors/5e343716a050db0018d20922?event_id=5e3437160055ff7001bc0000&i=gh&m=li)

**Comment by joshling1919** [comment]
@outoftime going to try to recreate this bug locally; any chance I could get the full stacktrace? Thanks so much!

**Comment by outoftime** [comment]
Sure thing!

```
TypeError Cannot read property 'toString' of undefined 
    validations/Validator.js:26:32 t.value
    validations/javascript/esprima.js:102:21 t.value
    validations/Validator.js:33:23 t.value
    node_modules/lodash-es/_arrayMap.js:16:20 t.a
    node_modules/lodash-es/map.js:50:14 t.a
    validations/Validator.js:21:23 t.<anonymous>
    node_modules/regenerator-runtime/runtime.js:45:39 tryCatch
    node_modules/regenerator-runtime/runtime.js:271:21 Generator._invoke
    node_modules/regenerator-runtime/runtime.js:97:20 Generator.forEach.e.<computed> [as next]
    https://popcode.org/mainAsync.db063acc05860c946617.js:1:878 h
--

**Comment by joshling1919** [comment]
@outoftime thanks so much!
