### ISSUE TITLE
Resizable editor windows

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#302]
Make it possible to resize editor windows by dragging them. Also make it possible to drag the center divider to change the width of the two main columns.

This seems like it should be a pretty straightforward feature, but I am honestly not sure of the right way to implement it given the current Flexbox-based layout!

**Comment by inlinestyle** [comment]
This is an interesting one... I don't know of a way to do it other than reverting to fixed `%` heights which would be painstakingly controlled at the `<Workspace>` level.

**Comment by outoftime** [comment]
@inlinestyle i was thinking the same thing but… [maybe not???](http://codepen.io/chriscoyier/pen/pJpbWK)

(i would prefer to avoid introducing jQuery but the conceptual approach would probably still work?)

**Comment by outoftime** [comment]
`<DraggableCore>` from https://github.com/mzabriskie/react-draggable looks like it would be just the thing for abstracting the actual mouse events into a drag

**Comment by inlinestyle** [comment]
@outoftime that jQuery UI solution is clever! And should port reasonably well to React. 

Do you have a timeframe for working on this? I'd take a stab at it tonight or tomorrow if you're not planning on doing it yourself in the near future.

**Comment by outoftime** [comment]
@inlinestyle it’s all yours! my focus right now is on making some architectural changes that I’m hoping will make the codebase more approachable for new contributors, and also make the application faster.

(speaking of which, one thing I’m a little concerned about is whether having drag events go through the entire Redux lifecycle is going to feel sluggish… if so, I definitely have some optimizations in mind)

**Comment by outoftime** [comment]
@inlinestyle btw, if you do start working on it, would you mind just assigning yourself the issue so no one else tries to grab it?

(Also let me know if that’s not possible—seems like as a popcode org member you should be able to, but you’re not coming up on the list when I click the assign button so maybe I need to do something else)

**Comment by inlinestyle** [comment]
@outoftime Hmm I'm not able to assign myself to any issues in this repo. According to [this](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) I should see a checkbox next to issues, which I don't...

![image](https://cloud.githubusercontent.com/assets/1098749/25161110/1700482e-2488-11e7-860f-0757865bd729.png)

^my interpretation:
- *you* as a write-access member should be able to assign to *me* as a read-access member
- only write-access members can assign issues.

**Comment by outoftime** [comment]
@inlinestyle weird, it isn’t giving me the option either. Oh well, no big deal really. Let me know how it goes!

**Comment by inlinestyle** [comment]
Hey @outoftime I've got a working demo on this branch: https://github.com/inlinestyle/popcode/tree/by-editor-resize

There are a few things that I'd love your input on before I file a PR:
1. I used `state` partly for performance and partly because it made for faster prototyping. I'm not sure whether you'd prefer this go through redux (I know linter is anti-`state`) or if you had other ideas.
2. I think that `_renderEditors` is a good candidate for being moved into its own component, e.g. `<EditorsColumn>`. I'd be happy to submit a PR doing that *before* submitting one for editor resizing, as it would allow for the resizing PR to be much more isolated.
3. I'm not happy with how I'm managing refs here. In `_storeEditorRefs` I'm inserting into `this.editorRefs` by index rather than `.push` because I don't think the `ref={...}` handlers are guaranteed to run in order. As a consequence of this I have to filter out `null` refs at the top of `_handleEditorDividerDrag` because minimizing a component can cause the ref to null out before `_renderEditors` gets run again. Any ideas on how to make this cleaner?
4. The decision tree in `_handleEditorDividerDrag` is a bit more complex than in the jQuery UI example because I made an attempt to address *some* of the glitches in the jQuery UI example:
    - The divider between the 2nd & 3rd sections is able to "push up" the divider between the 1st & 2nd in my version
    - Pulling the divider between the 2nd & 3rd sections below the minimum height of the 3rd section doesn't cause the height of the 1st section to decrease in my version

**Comment by outoftime** [comment]
@inlinestyle amazing!! initial quick responses inline:

> I used `state` partly for performance and partly because it made for faster prototyping. I'm not sure whether you'd prefer this go through redux (I know linter is anti-`state`) or if you had other ideas.

All else being equal, my preference is definitely for all state to be handled via Redux. However, performance might be a real concern here—there are some optimizations I’ve been meaning to make, but I do worry that pushing this through the Redux store might feel perceptibly laggy. That said, I’m curious as to what that would look like and how it would feel—would you be down to give it a shot? I think the actual code to push it through Redux should be pretty simple.

> I think that `_renderEditors` is a good candidate for being moved into its own component, e.g. `<EditorsColumn>`. I'd be happy to submit a PR doing that *before* submitting one for editor resizing, as it would allow for the resizing PR to be much more isolated.

Definitely!! In general I am 100% pro refactors of the form “decompose a big component into smaller ones”. In particular, the `Workspace` component is a giant ball of mud right now and I’ve already been intending to break it up. I can see how breaking out an `<EditorsColumn>` would make this change feel much more digestible.

> I'm not happy with how I'm managing refs here. In `_storeEditorRefs` I'm inserting into `this.editorRefs` by index rather than `.push` because I don't think the `ref={...}` handlers are guaranteed to run in order. As a consequence of this I have to filter out `null` refs at the top of `_handleEditorDividerDrag` because minimizing a component can cause the ref to null out before `_renderEditors` gets run again. Any ideas on how to make this cleaner?

I’ll need to put my hands on it, which unfortunately I don’t have time to do at this exact moment, but let me get back to you on that : )

> The minimum height of editors was chosen loosely based on whether the "Type in your * code here" text looked okay at that height for a range of normal browser widths. Happy to change....

I’m down with whatever you think is good on that front!

Overall: would you mind opening up a PR with this diff? Makes it easier to comment inline and such. Also as I said I’m definitely down for the initial PR of just reorganizing the editor column into its own component.

I’m really excited about this—sorry I don’t have more in-depth feedback right now but I will hit you back with more as soon as I can!

**Comment by inlinestyle** [comment]
@outoftime thanks for the feedback! 

As github has probably informed you I've filed the `<EditorColumns>` PR. I'll get to moving the resize stuff over to that branch this weekend. I'll also move the initial version over to `redux` 💪

**Comment by outoftime** [comment]
Fixed by #808 and #836
