### ISSUE TITLE
Publish to shareable URL

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#314]
Allow coders to “publish” their work to a stable, shareable URL.

A few approaches come to mind:

1. Export a gist that contains a single file with the fully-cooked page. Run the gist through [RawGit](https://rawgit.com/). Very simple! Not clear how this would work with [multi-page sites](https://github.com/popcodeorg/popcode/issues/786) though.
2. Push a project straight to a full-fledged GitHub repo, configured to publish to `gh-pages`. Definitely more work, but very nice and robust!
3. Set up a publicly-accessible S3 bucket, upload files directly to that (this is probably a bad idea)
4. Similarly, use something like [BitBalloon](https://www.bitballoon.com/features)

I think I’m leaning Option 2 at this point.

**Comment by outoftime** [comment]
Another interesting option: use `gh-pages`, as discussed [here](https://github.com/popcodeorg/popcode/issues/296)

**Comment by pwjablonski** [comment]
I'm interested in messing around with the rawgit solution.
