### ISSUE TITLE
“An <body> tag”

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#375]
Do the correct “A” vs. “An” in error messages. I suspect `i18next` has an affordance for this.

**Comment by schraj** [comment]
I agree that is seems like i18Next would have something out of the box for this : ) However, it is really more of an idiosyncracy of English so maybe not so much of an oversight on their part.

I don't love this answer, but it is the best I can think of using i18next.  i18next could handle it in the following way using a "format" function as part of the i18n interpolation process.

**Here is the key that you would use:**
"self-closing-non-void-element": "{{tag, en-handle-an-capitalized}} <{{tag}}> tag always needs a closing </{{tag}}> tag. Writing <{{tag}}/> is not allowed.",

**The "Format Keys": "en-handle-an"/"en-handle-an-capitalized" means the following:**
"en"-that this is only appropriate for "en" locale strings
"handle-an"-what it is doing
"capitalized"- that the A or An should/should not be capitalized.

**And here is the i18n init file:**

`import {init} from 'i18next';
import resources from '../../locales';

const getVariationOfAOrAn = function(value, capitalize) {
  const letters = ['a','e','i','o','u','h'];
  let firstLetter = value.substring(0,1);
  let correctWordForm = '';
  if (letters.find(function(l) {
    return firstLetter === l;
  })) {
    correctWordForm = capitalize ? 'An' : 'an';
  } else {
    correctWordForm =  capitalize ? 'A' : 'a';
  }

  return correctWordForm;
}

export default function() {
  init({
    fallbackLng: 'en',
    resources,
    interpolation: {
      format: function(value, format, lng) {
        if (format === 'en-handle-an') return (!lng || lng === 'en') ? getVariationOfAOrAn(value, false) : '';
        if (format === 'en-handle-an-capitalized') return (!lng || lng === 'en') ? getVariationAOrAn(value, true) : '';
        return value;
      }
    }
  });
}
`

**Comment by outoftime** [comment]
@schraj this is a really cool proposal! My only (fairly superficial) feedback:

* I like the idea of including `en-` in the formatter name for self-documentation, but I don’t think we would need the check in the `format` function, since presumably the formatter would only be referenced in English translation files, right?
* Is it possible to compose two formatters? Seems like it would be nice to decouple the capitalization from the a/an of it all

That being said, I think this is a really clever approach and I’d love to go for it. Are you down to cook up a PR along those lines?

**Comment by schraj** [comment]
sure, I'll do this in the next couple of days.

**Comment by outoftime** [comment]
Fixed by #773

**Comment by outoftime** [comment]
@schraj it’s out! I noticed there are several more messages in the translations file that would benefit from this—would you be down to follow up? I can handle if you’ve had enough a/an for now : )
