### ISSUE TITLE
No errors when high-level document structure is wrong

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#378]
Things that Popcode currently allows:
### `head` inside `body`

``` html
<!doctype html>
<html>
<body>
  <head><title></head>
</body>
</html>
```
### `body` inside `head`

``` html
<!doctype html>
<html>
  <head>
    <body></body>
  </head>
</html>
```
### Text outside root

``` html
<!doctype html>
Hello, world!
<html>
  <head>
    <body></body>
  </head>
</html>
```
### Text inside `head` tag:

``` html
<!doctype html>
<html>
<head>
        <title>Page Title</title>
        asdf
</head>
<body>
</body>
</html>
```
### Text directly inside root node

``` html
<!doctype html>
<html>
Hello, world!
<head>
  <title>Something</title>
</head>
<body>
</body>
</html>
```
### Content tag inside `<head>`

``` html
<!doctype html>
<html>
<head>
  <title>Something</title>
  <p>Hello, world!</p>
</head>
<body>
</body>
</html>
```
### Content tag between `<head>` and `<body>`

``` html
<!doctype html>
<html>
<head>
  <title>Something</title>
</head>
<p>Hello, world!</p>
<body>
</body>
</html>
```
### Content tag outside document structure

``` html
<!doctype html>
<p>Hello, world!</p>
<html>
<head>
  <title>Something</title>
</head>
<body>
</body>
</html>
```

Unfortunately, none of our linters/parsers actually complain about these problems.

A couple of possible approaches come to mind; neither is easy:
- Submit an upstream patch to [slowparse](https://github.com/mozilla/slowparse) to add errors when this happens. I haven’t looked at slowparse’s code much, but philosophically this seems like the sort of error it should catch. It also may be abandoned at this point (but we can always just target a fork)
- Use the `Parser` class in [`html-tokenizer`](https://github.com/greim/html-tokenizer). This generates a DOM tree structure from an input string. The good news is, unlike the parsers built into browsers, it _doesn’t_ enforce a valid DOM structure in its output—so if your HTML has a `<body>` tag inside a `<head>` tag, it’ll give you a DOM tree with a `body` element inside a `head` element. Obviously we’d need to hand-roll the actual validations, but that seems tolerable, and we could probably get some low-hanging fruit by implementing some very simple rules (e.g. `<html>` contains only `<head>` and `<body>`; `<head>` and `<body>` are direct descendants of `<html>`
  - As a corollary: Maybe we could use `html-tokenizer` to generate a highly literal DOM tree, then feed it in to [`html-inspector`](https://github.com/philipwalton/html-inspector), which makes a lot of assertions about correct DOM structure already?
  - Chrome, at least, allows us to manually construct invalid DOM fragments, e.g. I can call `doc.head.appendChild(doc.createElement('body'))` and I will get a tree with a `<body>` inside a `<head>`
  - A quick console test suggests that `html-inspector` does not catch this particular problem out of the box, but it is pretty extensible!

**Comment by megknoll** [comment]
Add to ticket: Also no errors when content tags ... <p>, <h1>, <img>, etc... are outside of the <body> tag, outside of the root, inside the <head> tag, etc.

**Comment by outoftime** [comment]
@megknoll updated!
