### ISSUE TITLE
Preview document title should be window title

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#386]
The title of the Popcode tab should be whatever the student has entered into the `<title>` tag in the HTML, ideally _as long as they have changed it from the default_. No particularly elegant way to satisfy that second requirement comes to mind.

Seems like we could use the [`react-element-portal`](https://github.com/zapier/react-element-portal) library for the time being, and switch to React 16’s built in implementation of portals once that’s out.

**Comment by ianmclaury** [comment]
Giving this a shot

**Comment by maxjacobson** [comment]
@outoftime mind unassigning me?

**Comment by outoftime** [comment]
@maxjacobson done!

**Comment by outoftime** [comment]
I think we’re good here now that the page title is reflected in the preview chrome.
