### ISSUE TITLE
Project titles are often blank

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#502]
I’ve noticed that project titles are often blank in students’ project lists. I forget where we derive the title from, but obviously there needs to be better fallback. Also, it might make sense to add more emphasis to the date of the project and deemphasize the content preview.

**Comment by carolchau** [comment]
I think adding more emphasis to the date does make more sense. 

What do you think of the idea where the content preview only displays text between title tags ? And if there are no title tags, or if there's no text, then the content preview displays 'Untitled Project'?

**Comment by outoftime** [comment]
> What do you think of the idea where the content preview only displays text between title tags ? And if there are no title tags, or if there's no text, then the content preview displays 'Untitled Project'?

@carolchau not a bad idea!

**Comment by outoftime** [comment]
Fixed by #794
