### ISSUE TITLE
Opening new windows doesn’t work in IE

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#508]
Neither IE nor Edge supports HTML data URIs.

Either need to come up with a different approach (open `about:blank` followed by a `document.write`?) for IE and Edge, or perhaps just use an approach that works in all browsers.

**Comment by outoftime** [comment]
@jwang1919 can you fill in the details here when you get a chance? Thanks!!

**Comment by jwang1919** [comment]
Does it work for all browsers to open `about:blank` and then a `document.write`?
If not I would favor the latter. Not a fan of writing extra code to support 2 browsers that are sparsely used.

**Comment by outoftime** [comment]
> Does it work for all browsers to open about:blank and then a document.write?
If not I would favor the latter. Not a fan of writing extra code to support 2 browsers that are sparsely used.

Yep, I think that does work in all scenarios.

**Comment by outoftime** [comment]
Popcode no longer supports IE at all.
