### ISSUE TITLE
Make it possible to minimize the preview pane

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#514]
Particularly when demonstrating code on the board, it might be helpful to have the preview pane minimized to make more space for the editors. We can probably just put a minimize button next to the pop-out button, and have it minimize to the sidebar in the same way the editors currently do.

**Comment by jwang1919** [comment]
While PR #131 is still pending, I'll take a look at this. This looks like a simple task with a big upside.

**Comment by outoftime** [comment]
Fixed by #554
