### ISSUE TITLE
Error message for improperly nested <li> is confusing the students

### ISSUE THREAD

**Issue by filapinoaquino** [popcodeorg/popcode#515]
If `<li>` is not properly nested the error message reads "The `<li>` tag can’t go inside the `<body>` tag."  Maybe we can do a poll to figure out a more helpful error message.

`<!DOCTYPE html>
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>
        <li></li>
    </body>
</html>`

**Comment by outoftime** [comment]
Word! Here’s what I wrote in another ticket:

> E.g. when there is an `<li>` that isn’t in a `<ul>`/`<ol>`, the error message should say as much, rather than just complaining that it’s inside a `<div>` or whatever.

> I think we would just special-case specific tags that are particular about their parents, and use the current message as the generic one.

**Comment by alexpelan** [comment]
Gonna take a look at this one next

**Comment by outoftime** [comment]
@alexpelan all yours!
