### ISSUE TITLE
Add link to Slack signup to README

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#519]
Slack signup lives at https://slack.popcode.org. The README should link to it.

**Comment by leo-alexander** [comment]
Hi! Keen to contribute, this looks like a good starting point.

**Comment by outoftime** [comment]
@leo-alexander sure, sounds great!

**Comment by outoftime** [comment]
(Also would be good to mention the `#dev` channel specifically!)

**Comment by outoftime** [comment]
Fixed by #766
