### ISSUE TITLE
Allow undefined variables if HTML contains an external script

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#544]
If students load an external script on to the page by putting a `<script>` tag in the HTML, we can no longer assume that all global variables are known to us. So, in that case, we should turn off the `jshint` check for undefined variables.

This would, for instance, allow Popcode to afford a Tiny Turtle project without explicitly supporting it.

**Comment by alexpelan** [comment]
Think I might take a look at this one next - sound good?

**Comment by outoftime** [comment]
@alexpelan sure!!
