### ISSUE TITLE
Long url in <img> completely hides HTML/CSS/Javascript panels during error

### ISSUE THREAD

**Issue by purplecones** [popcodeorg/popcode#548]
I came across this issue while working with a student a few days ago. The gist in question that causes this popcode issue can be seen [here](https://gist.github.com/Margauxmantrand/d9fb840273e03d9a523fdf2a3060fccc). 

The cause appears to be the length of url. When the error description is shown, the error pane pushes the HTML/CSS/Javascript until the panes are completely hidden. Perhaps long continuous strings should have a max length and wrap accordingly.

```
<img src:"https://www.google.com/search?q=mihs&safe=strict&espv=2&biw=1632&bih=905&source=lnms&tbm=isch&sa=X&ved=0ahUKEwijrLelzPjPAhVMOz4KHbfTCx0Q_AUICCgD#safe=strict&tbm=isch&q=manhattan+international+high+school&imgrc=jTYtEPRLxG2RAM%3A
```

In this particular case, the student used the google search URL instead of the image URL by mistake. Fortunately we were able to export the project so no work was lost.

![popcode issue](https://cloud.githubusercontent.com/assets/136654/20106709/1ab2439a-a5a4-11e6-933f-eac67dcf1de0.gif)

**Comment by outoftime** [comment]
Yikes! Good catch!
