### ISSUE TITLE
Why no .bowerrc?

### ISSUE THREAD

**Issue by purplecones** [popcodeorg/popcode#550]
I noticed this project does not have a .bowerrc file but is using bower to bundle dependancies. I was not able to get it to run because it was complaining the the bower_components folder was missing. 

After adding a .bowerrc file in the root with 
```
{
  "directory": "bower_components"
}
```
I got it to work. 

I don't normally use bower so I might be missing a step. Let me know and I'll close issue.

Thanks

**Comment by outoftime** [comment]
Hmm! I’m no Bower expert and have not run into this issue either in my environment or in CI (or on other contributors’ machines). However I certainly would be happy to accept a PR that adds it in!

**Comment by jessewang-arvatosystems** [comment]
Hmm.. bower should be automatically included in the npm install step.

**Comment by purplecones** [comment]
That's what I assumed but following the steps:

```
$ npm install
```
```
$ gulp dev
```

never created a `bower_components` folder for me

**Comment by outoftime** [comment]
@purplecones very strange—but if you delete `bower_components` and run those steps with a `.bowerrc` it works?

**Comment by alexpelan** [comment]
fwiw, I also have had issues with bower_components not getting created - could you have a global .bowerrc that it's falling back on?

**Comment by outoftime** [comment]
@alexpelan maybe! i don’t have one in my home directory but maybe something magically configured by boxen…

**Comment by jwang1919** [comment]
Oops was on my work github account. 

@purplecones I do remember I configured a bower_components dir manually when the `npm install` was failing for me on Windows due to `fsevents`. When I got the `npm install` working I didn't have this problem again. 

Maybe @outoftime is right something else is happening. I need to get back home to confirm.

**Comment by purplecones** [comment]
@outoftime yea. Doing a fresh `git clone` and `npm install` does not create the bower_folder for me.  However, adding the `.babelrc` file and running `bower install` does create it.

**Comment by jwang1919** [comment]
@purplecones I tried a fresh build, uninstalled bower from global npm libraries. Still couldn't reproduce this  bug. When running `npm install` do you see something like this in the logs?
```
> popcode@0.9.0 postinstall C:\Users\jwang\Desktop\test\popcode
> bower install
```

**Comment by outoftime** [comment]
I’ve never heard of anyone else seeing this bug, nor have I had the problem when checking out the project on different machines. Gonna go ahead and close.
