### ISSUE TITLE
Misleading error when a closing tag is missing

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#562]
Submitter: Kate Miller
Here is the code:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>
     <h1>My Web Page</h1>
        <p><a href="//google.com">
            Go to Google
    </a>   
    </body>
</html>
```

Here is the error:

```
11
Your <p> tag needs a closing tag, but instead there’s a </body> tag where the </p> tag should be.
```

This error was confusing, because in reading it without thinking about it, my first instinct was to replace the closing body tag with a closing p tag which then of course led me to another error...

```
12
Your <body> tag needs a closing tag, but instead there’s a </html> tag where the </body> tag should be.
```

Which led me to replace the closing html tag with a closing body tag...

I think the wording of that original error is confusing. By saying there is a closing body tag where the closing p tag should be immediately make you think replacement. A better error message might be "closing p tag is missing"

**Comment by outoftime** [comment]
This would be a good one to experiment with the idea of trying out heuristic fixes to narrow down what the error case is. I think in some cases (e.g. closing tags are in the wrong order, rather than one is missing), the error message here _is_ the right one, and the information we get from the linter isn’t enough to distinguish between the two. But we could try heuristically putting the closing tag where the error occurs and then seeing what the linter says. If it fixes it, we know it’s a missing tag; if not, we can show the existing message.

**Comment by tenyoung795** [comment]
Speaking with @inlinestyle, I proposed that, for a given lexable HTML that suffers from a missing closing tag, check the set S of tokens (including closing tags) after the token T where the missing closing tag was detected. If the expected closing tag does not exist in S, then we can conclude to add the closing tag right after token T.

I think that'd require lexical analysis; could [html-lexer](https://www.npmjs.com/package/html-lexer) be useful?

Perhaps more sophisticated lexical analysis could even pinpoint that closing tags are in the wrong order; e.g. the expected closing tag actually exists in s?
