### ISSUE TITLE
Long URLs in error messages take over screen

### ISSUE THREAD

**Issue by ericandrewlewis** [popcodeorg/popcode#598]
<img width="1258" alt="screen shot 2016-12-06 at 9 36 05 pm" src="https://cloud.githubusercontent.com/assets/1087646/20952662/0e96b0be-bbfc-11e6-8b55-144d81a666b0.png">

**Comment by outoftime** [comment]
Hey @ericandrewlewis thanks for the report! We’ve already got an issue open for this at #548 and a proposed fix in #549, although the latter relies on the `word-break` CSS property, which will make error messages harder to read by breaking/hyphenating words even when doing so isn’t particularly necessary.

I took a stab at getting better behavior (basically we just want to break very long “words”) but ran up against my ability to reason about flexbox behavior. Do you have any idea how you might go about fixing this?

Anyway, going to close this so we can continue tracking in #548

**Comment by ericandrewlewis** [comment]
Ah thanks for the dupe! I'll look at the PR 😄
