### ISSUE TITLE
Save snapshot of editor state for grace period when closing tab

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#609]
As of now, if a student is logged out, closing the window will cause all work in progress to be lost. There is a confirm dialog, but that approach isn’t especially effective at preventing unintentional loss of work.

Instead, we should save a snapshot of the entire application state any time the user closes a Popcode tab. If a new Popcode instance is opened within some short time window (I’m thinking something in the range of 1–5 minutes), the application state is restored to exactly what it was when the window was closed. This would in effect provide an “undo”-like functionality for closing the environment.

I think this is worth doing in all scenarios, regardless of login state.

To be clear, this should *only* happen in scenarios where Popcode is closed and then reopened in quick succession. So we want this:

1. Student is working in Popcode
1. Student closes the Popcode tab
1. Student opens Popcode in a new tab
1. State of editor at the time it was closed is restored

But also:

1. Student is working in Popcode
1. Student opens a second Popcode tab
1. The new Popcode tab is a pristine environment with no relationship to the first one.

I think the approach here would be to just save the entire Redux state tree to local storage on window unload. From what I’ve read, it’s important to use actual local storage rather than something like IndexedDB, as the latter is asynchronous and will not reliably complete an operation before the page is torn down. It looks like Transit offers a good way to serialize an ImmutableJS data structure, which would be useful here.

**Comment by ajgreenb** [comment]
I think this can be closed?

**Comment by outoftime** [comment]
Yep yep yep!
