### ISSUE TITLE
Installing gulp is not mentioned in local dev instructions

### ISSUE THREAD

**Issue by ericandrewlewis** [popcodeorg/popcode#610]
The local development instructions say the user should run 

`$ gulp dev`

I didn't have this on my computer and then installed gulp globally via 

`$npm install -g gulp`

**Comment by ericandrewlewis** [comment]
We could instruct users to install gulp globally via npm. Alternatively, since gulp is a project dependency, we could add an npm script for local dev

```
"scripts": {
   "dev": "gulp dev"
}
```

and for local development instruct users to run 

`npm run dev`

**Comment by outoftime** [comment]
@ericandrewlewis `gulp` is a [development dependency](https://github.com/popcodeorg/popcode/blob/master/package.json#L119)—were you unable to run `gulp dev` after running `yarn install`?

(I still like the idea of a `dev` script, and in fact I’d argue for it to include a `yarn install` before running `gulp dev`)

**Comment by ericandrewlewis** [comment]
> @ericandrewlewis gulp is a development dependency—were you unable to run `gulp dev` after running `yarn install`?

Yes. Yarn installed the gulp package at `node_modules/gulp` and made a binary version available at `node_modules/.bin/gulp`, but running `gulp` on the command line results in an error like this without installing the module globally

```
$ gulp dev
-bash: /usr/local/bin/gulp: No such file or directory
```

**Comment by outoftime** [comment]
@ericandrewlewis I think it’s fairly common to have `./node_modules/.bin` on one’s `$PATH`—should that not be assumed?

**Comment by ericandrewlewis** [comment]
> I think it’s fairly common to have ./node_modules/.bin on one’s `$PATH`— should that not be assumed?

I've never heard of it before, although a Google search shows that others do it. I'd say we should not assume it, to support contributors getting up and running without hitting snags along the way.

**Comment by outoftime** [comment]
@ericandrewlewis OK, fair enough—I’m down to add a `dev` script and change the instructions in the README. Want to hit me with a PR?

**Comment by ericandrewlewis** [comment]
Sure! One q:

> (I still like the idea of a `dev` script, and in fact I’d argue for it to include a `yarn install` before running `gulp dev`)

What is the intent of running `yarn install` before `gulp dev`? The user should have their dependencies installed previously, is the intent to make sure they're up to date?

**Comment by outoftime** [comment]
Yep, exactly!
