### ISSUE TITLE
JavaScript doesn’t run at at all when output is hidden

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#629]
Submitter: Erica Wong
When you are using the console, you need to have the output open for it to run. This is problematic when you are projecting to a screen in front of the whole class. It would be nice if you could close the output so you can zoom in and see everything clearly!

**Comment by outoftime** [comment]
@jwang1919 this is a juicy one! are you down to take a look? probably pretty easily fixed by `display: none`ing the output if it’s hidden, rather than removing it from the DOM entirely…

**Comment by jessewang-arvatosystems** [comment]
@outoftime yeah sure. This doesn't look too bad.

**Comment by outoftime** [comment]
Fixed by https://github.com/popcodeorg/popcode/pull/631
