### ISSUE TITLE
Make it more obvious that you can log in

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#638]
It’s not very obvious that you can log in to Popcode, or that in general it’s possible to save your work. The most straightforward solution would be to expose a log in button that’s visible by default. Unfortunately, there isn’t a great place to put that in the current layout.

A few ideas, courtesy of @iamnickvolpe:

### Always-open header + opening side dashboard

Clicking the gear would reveal the dashboard

![image](https://cloud.githubusercontent.com/assets/14214/22765138/b139066a-ee3c-11e6-8569-7a2df949d575.png)

### Condensed always-open side dashboard

![image](https://cloud.githubusercontent.com/assets/14214/22765147/b7fbcc6c-ee3c-11e6-8101-bf1c0c215b39.png)

**Comment by iamnickvolpe** [comment]
<img width="1295" alt="screenshot 2017-02-09 17 47 45" src="https://cloud.githubusercontent.com/assets/3432105/22806420/f7efc22a-eeef-11e6-8122-0a5b721391c9.png">

Another exploration based on the suggestion to add it to the "closed" sidebar. Obviously, this isn't as clear as the others but could be an improvement for some users.

**Comment by outoftime** [comment]
We are good here after this summer’s design overhaul.
