### ISSUE TITLE
Tool for pretty-formatting code

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#639]
Per @ericascripted

It would be nice for students to have a tool to pretty-format their code, a feature many IDEs have built in.

While ideally we would like for students to be conscientious about formatting their code as they write it, this is an unrealistic ambition. By giving students an easy way to format the code they’ve written, we may develop a sense of well-formatted code looking “right” for students, and thus indirectly cultivate habits of good formatting while writing.

In terms of UI, I think we could repurpose the editor labels to expose a small tool menu rather than directly hide the editor. One of the tools would be to hide; the other, to format the code. I’m open to other suggestions, of course.

**Comment by ianmclaury** [comment]
What about as-you-type? I imagine incremental format changes would be easier for a student to take in -- as opposed to suddenly-all-at-once where there might have been a dozen changes. Maybe the format tool would be to turn autoformat on or off?

Also -- though definitely a stretch goal -- it would be really cool for some command/action to show the student a slow-motion animation of the formatting being applied, change by change.

**Comment by ericascripted** [comment]
Like a squiggly line under what you type like Google Docs when you misspell
or have poor grammar?

Erica Wong | Program Manager
*ScriptEd, Inc.*
917-946-4881 <(917)%20946-4881>
85 Broad Street, New York, NY 10004
erica@scripted.org | scripted.org
Follow ScriptEd on Twitter @scriptedorg <http://twitter.com/scriptedorg>
Follow me on Twitter @ewwong <http://twitter.com/ewwong>

Hire a ScriptEd intern <http://scripted.org/opportunity> this summer!

**Comment by outoftime** [comment]
@ianmclaury I too am intrigued and wondering how you’d envision as-you-type formatting working? Popcode already does basic auto-indentation via the built-in behavior of the ACE editor—would this go beyond that?

**Comment by ianmclaury** [comment]
Sorry for the slow response! I was thinking of just running [prettier](https://github.com/prettier/prettier) against the js editor contents on every update.

That UX seems pretty aggressive so I'm not sure it would be that simple - maybe it would be an extra button or a mode or something. It would definitely need some experimentation to see whether it's useful at all.

That said, in my own code I've been much more pleased with prettier's formatting than I ever expected to be.

**Comment by outoftime** [comment]
i could see maybe putting line-level indicators where formatting is needed, and then clicking the indicator would format just that line? not sure exactly how one would implement that though

**Comment by outoftime** [comment]
Superseded by #1168
