### ISSUE TITLE
Users click into CSS pane thinking it's still the HTML pane

### ISSUE THREAD

**Issue by ericandrewlewis** [popcodeorg/popcode#708]
I've seen a few users click into the CSS editor and start typing HTML thinking it's still the HTML editor. 

I think we could add some border to demarcate the separate code editors.

**Comment by outoftime** [comment]
@ericandrewlewis agreed! i’ve noticed this as well. are you down to cook up a PR?

**Comment by ericandrewlewis** [comment]
Thinking about the problem a bit more, I thought of another way to approach it.

We could give the inactive editors a dimmed state. This might signal users more clearly what editor has the focus, and make them aware of the switch if they accidentally click into the next editor. 

I am new to ACE editor, it seems like we would have to fork the editor theme we're using to add styles like this.

![1 mov](https://cloud.githubusercontent.com/assets/1087646/23589276/f34819b0-0197-11e7-89df-9706dbeef535.gif)

Or, we could add a border a la

<img width="1119" alt="screen shot 2017-03-05 at 11 36 02 am" src="https://cloud.githubusercontent.com/assets/1087646/23589343/1e9ffcda-0199-11e7-9f79-57bfa2851b71.png">

**Comment by outoftime** [comment]
@ericandrewlewis I love the idea of an active/inactive state for editors, although I’m not sure it’s an either/or proposition—I would say it’s particularly important to have a clear delineation between the editors when none are focused. So, border seems like a good move regardless. I like what you’ve got in that screenshot.

In terms of the inactive state—one thing we could do is just drop an absolutely positioned semi-transparent `<div>` over the editor. A little hacky but probably worth avoiding having to fork `brace` (which is quite baroque in how it’s built).

I do wonder if what you’ve got in that animation is a little visually intense though? Possibly distracting? I’m not sure. Maybe just a subtler shade would do the trick.

**Comment by ericandrewlewis** [comment]
Cool, I've opened a PR for the border to start.
