### ISSUE TITLE
Error when functions are declared below function call

### ISSUE THREAD

**Issue by megknoll** [popcodeorg/popcode#719]
Popcode is reporting an error when functions are declared below where they are called.  
It should only enforce that rule for actual var declarations, not for function declarations, which specifically *are* okay to declare below calling.

**Comment by alexpelan** [comment]
Here's a reduced gist: https://gist.github.com/alexpelan/59caa995e2694d41170623365711294f

**Comment by schraj** [comment]
This looks to have to been a design decision by JSLint to consider use of "hoisting" a bad practice. JSHint has added the option to override it if you want to.  

http://jshint.com/docs/options/#latedef

I've added a pull request to override it.

**Comment by outoftime** [comment]
Fixed by #761
