### ISSUE TITLE
Line number is ambiguously presented in error panel

### ISSUE THREAD

**Issue by ericandrewlewis** [popcodeorg/popcode#724]
When I see errors, I see a number on one line and then a description of the problem after it:

<img width="533" alt="screen shot 2017-03-26 at 3 03 28 pm" src="https://cloud.githubusercontent.com/assets/1087646/24334268/73e23904-1235-11e7-84e3-c7239f2003b7.png">

I wonder if we could provide context that the number represents the line number the warning is for.

**Comment by ericandrewlewis** [comment]
Maybe:

```
On line 8:
Your <p> tag needs a closing tag, but instead there’s a </body> tag where the </p> tag should be.
```

**Comment by outoftime** [comment]
@ericandrewlewis I’m down! want to cut a PR?
