### ISSUE TITLE
does not work when deployed to sub-directory

### ISSUE THREAD

**Issue by freder** [popcodeorg/popcode#769]
URLs in [static/index.html](../tree/master/static/index.html) (and elsewhere) should be relative

**Comment by outoftime** [comment]
@freder what’s the use case?

**Comment by freder** [comment]
@outoftime I'd like to host popcode on `my.own.server/teaching/popcode`

**Comment by outoftime** [comment]
@freder OK, fair enough—you’d set up your own Firebase account etc.?

Anywho, I’d definitely accept a PR that makes running it in a subdirectory work smoothly!

**Comment by freder** [comment]
@outoftime  the main reason to host it myself would be for the students to find all material and resources in one place. another thing I might do is add more libraries, or remove some that I don't talk about in class.

I'm not super familiar with firebase yet. — would you like me to set up a separate account in this case?

**Comment by outoftime** [comment]
@freder yes please—the default is a dev account that I’m totally fine with people using for local development but shouldn’t be used in a live environment (I may reset it at any time). In general I’d suggest looking at the configuration for the WebPack environment plugin for things you’ll need to configure yourself (it’s not a lot):

https://github.com/popcodeorg/popcode/blob/master/webpack.config.js#L174-L182

Feel free to ping me with any questions.

Also if you do move forward with your own deployment, it would be _great_ if you could keep notes on what you needed to do, as a resource for anyone else who wants to do this in the future!

**Comment by outoftime** [comment]
Also, for stuff like adding more libraries, please keep me informed of where the canonical codebase isn’t sufficient. I’m definitely open to adding more to the current list.

**Comment by outoftime** [comment]
Fixed by #770
