### ISSUE TITLE
Project instructions

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#780]
We would like for instructors to be able to distribute instructions with project starter code. Currently, this is done by way of inline comments in the starter code, but students find this confusing.

While project instructions will certainly be part of a larger project assignment-submission flow currently planned for spring of 2018, we’d like to do something simpler sooner.

Initial pitch would be:

* After exporting starter code to a gist, instructors can add a new file with a certain name e.g. `instructions.md`, with project instructions in Markdown
* When Popcode imports a gist, it’ll look for this entry and, if present, display the instructions in their own pane (probably above/below the output?)
* Instructions should be saved with the project, so that loading the project again later will retain the instructions
* When exporting a gist, the instructions should be included (mostly to make it easy for instructors to import a sample project, make some modifications, and then re-export for their class).

Not having the ability to actually write instructions in Popcode is obviously not amazing, but I’d like to see if it’s enough to tide us over until we build the full assignment workflow. If not, we can always follow up with instruction creation/editing functionality.

**Comment by inlinestyle** [comment]
@outoftime regarding the name of the `.md` file - 
It looks like project import [as implemented](https://github.com/popcodeorg/popcode/blob/master/src/reducers/projects.js#L42) concatenates all available `.css` and `.js` files. Would it make sense to do the same with `.md` files, i.e. find, concatenate, and display them all?

**Comment by outoftime** [comment]
@inlinestyle sure, that seems like a more satisfying approach than having a specific magic filename hard-coded in

**Comment by outoftime** [comment]
Closed by #988

**Comment by outoftime** [comment]
_Actually_ closed by #1033 #1000
