### ISSUE TITLE
FR: Support hiding HTML/CSS/javascript panels on load

### ISSUE THREAD

**Issue by marcianx** [popcodeorg/popcode#807]
This is a minor feature request.

Just like PopCode currently stores a JSON in the gist remembering whether, e.g., jQuery was enabled in the library settings, I would love it if it would also remember which HTML/CSS/javascript panes were open OR, like jsbin, allow showing only a subject of panes (e.g. http://jsbin.com/?html,output shows only the HTML and output panes, hiding the rest).

While teaching for ScriptEd, I have to constantly tell my students to hide, e.g. the CSS and HTML panels and focus on the javascript pane where I have tasks for them. Skipping this verbal step would be nice to help keep students focused on only what I'd like them to.

**Comment by inlinestyle** [comment]
This might be echoing https://github.com/popcodeorg/popcode/issues/799, with PR out https://github.com/popcodeorg/popcode/pull/806. Guess it's a popular enhancement!

**Comment by marcianx** [comment]
Yes, thank you. This is indeed a duplicate. I was not able to find it with the searches I'd tried.
