### ISSUE TITLE
External starter code scripts can’t use libraries

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#815]
If you, for instance, write an external starter code script and host it on RawGit, the script can’t access jQuery, because the jQuery tag is put at the very bottom of the parsed DOM body.

Instead, we should put library scripts at the top of the `<head>`, so that other scripts can use them.

**Comment by jwang1919** [comment]
After inserting jQuery library in the head tag, still having issue running jQuery from a raw git script file. FMI see: https://github.com/jwang1919/popcode/tree/%23815-external-starter-code
