### ISSUE TITLE
Clean up notification UI

### ISSUE THREAD

**Issue by outoftime** [popcodeorg/popcode#838]
Notifications don’t currently look great:

![image](https://cloud.githubusercontent.com/assets/14214/26529557/d5722108-438f-11e7-84cc-e81ac5600450.png)

Worst part is the misaligned close box, but could probably generally look a little fresher.

**Comment by pwjablonski** [comment]
Submitted pull request 
![screen shot 2017-06-04 at 3 04 07 pm](https://cloud.githubusercontent.com/assets/9774128/26764573/20eeede4-4937-11e7-8e8a-d0c57cb8a1ca.png)
