### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by courtney-scripted** [popcodeorg/popcode#969]
Hi Mat (and Popcode Team),

With the new login feature I don't see my username anywhere on the screen. I'm concerned that students who share computers won't realize that they aren't logged into their own accounts. Can you please make sure that username is visible when students login?

Thanks,
Courtney

**Comment by outoftime** [comment]
Thanks @courtney-scripted ! For posterity—Popcode does the right thing if your GitHub account has a real name in it; but if not, it should fallback to the username, which it currently doesn’t.
