### ISSUE TITLE
Gist import broken?

### ISSUE THREAD

**Issue by ianmclaury** [popcodeorg/popcode#981]
On clicking a gist import link, the popcode "Loading" throbber page appears but never loads.

Steps to reproduce:
1) open https://popcode.org, which presents a new, blank project
2) log in to github
3) choose "export gist" from the sidebar
4) wait for the exported gist to load on gist.github.com
5) follow the "click to import" link on the gist
6) observe that the gist never loads

This happened on all the gist import links I tried, not just the trivial starter projects. Observed in Safari 10.1.2 and Chrome 60.0.3112.90 on OS X 10.11.6 El Capitan.

**Comment by outoftime** [comment]
Good catch! Fix on the way
